### ISSUE TITLE
space issue

### ISSUE THREAD

**Issue by CorvoApp** [gregoiresage/fitfont#2]
Steps to reproduce:

1. Create any custom font
2. Add a space in the text
3. Error about character not found should be thrown during the build

> App: Char not found   in Random_Font_30

**Comment by gregoiresage** [comment]
If you have a dynamic text, how would you detect a character is missing during the build?
It's up to you to generate all the possible characters for your app, no?

**Comment by CorvoApp** [comment]
Even if I add the space character to the list of chars to be generated, this won't get generated as image file, it will be simply skipped.
That's why of the error about not finding the char.

**Comment by CorvoApp** [comment]
I did some research and found that the problem is caused by:

1. Windows which seems to drop any space character in the script arguments so the raw string doesn't even reach the script, to make it work as it should I had to escape double quotes ( \"1 2\" )
2. generate.py script : you check for char height and since the space char has no height it's going to be skipped  https://github.com/gregoiresage/fitfont/blob/63b47699d193d53881d7d9f158619c9552691af7/generate.py#L40

**Comment by gregoiresage** [comment]
Yes you have to double quotes the list of characters if it contains a space
For the point 2, I don't generate empty images, it is useless. It should not be a problem during runtime, the image will not be found so nothing will be displayed, this is what we want. But the width of the space character is used to calculate the position of the next characters.

**Comment by CorvoApp** [comment]
Not really true I guess, there is no space in between 13 and OCT but in my string there is a space ( "13 OCT") so the space width is not calculated or not applied I guess.

![Capture](https://user-images.githubusercontent.com/52882875/66717414-ae9cc180-edd0-11e9-9fe9-efae1cdf86a0.PNG)

**Comment by gregoiresage** [comment]
It is working for me with my fonts...
In the generated json file I have something like that for the sapce character `" ": [11, 0, 0, 61, 11]`
Do you have an entry for the space char in yours ?

**Comment by CorvoApp** [comment]
Unfortunately I don't have any space entry in the json file.

I cannot attach json files here so I'll post a pastebin link: 
https://pastebin.com/ZKqRCCp8

**Comment by gregoiresage** [comment]
You need to generate the file with the space character :
`npx fitfont-generate /path/to/my_cool_font.ttf 200 "0123456789:. ABCDE"`

Can you share your ttf file?

**Comment by CorvoApp** [comment]
Ok, I finally solved this, the problem was not your script, it was windows dealing with quoted arguments:

Example: 
`npx fitfont-generate UNICORN_REGULAR.TTF 30 "0123456789:. ABCDE"` would split the string in two parts using the space as a delimiter which then produce the following arguments:
`[ 'C:\\Program Files\\nodejs\\node.exe',
  'C:\\Users\\Admin\\Test\\node_modules\\fitfont\\bin\\generate.js',
  'UNICORN_REGULAR.TTF',
  '30',
  '0123456789:.',
  'ABCDE' ]`

That was the issue and I'm feeling stupid to not find this before opening this issue.

Almost forgot: the solution is to escape double quotes `npx fitfont-generate UNICORN_REGULAR.TTF 30 \"0123456789:. ABCDE\"`

Feel free to close this.
