### ISSUE TITLE
Feature request : Zoom / Scaling

### ISSUE THREAD

**Issue by lambtor** [gregoiresage/fitfont#6]
Any chance of adding the ability to set a scaling for the characters?  I understand this would lead to pixelation when zoom factor gets large, but this could be a nice option to avoid the need to export fonts to multiple sizes.

**Comment by gregoiresage** [comment]
Hello, just put your text in a group and apply the scaling on the group.
The scaling will be also applied to the children.
No need to make a specific implementation in fitfont 😀

**Comment by lambtor** [comment]
Yes, I just found how to do the scaling with a group element.  thank you for building this.
